"""empty message

Revision ID: 2201a5ec6092
Revises: 3d3bce84e782
Create Date: 2023-12-02 16:23:55.636649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2201a5ec6092'
down_revision = '3d3bce84e782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_connected', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_user', schema=None) as batch_op:
        batch_op.drop_column('date_connected')

    # ### end Alembic commands ###
