"""empty message

Revision ID: 3d3bce84e782
Revises: f75f9a61e7ce
Create Date: 2023-12-02 16:23:10.152256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3bce84e782'
down_revision = 'f75f9a61e7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_connected', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connected_user', schema=None) as batch_op:
        batch_op.drop_column('date_connected')

    # ### end Alembic commands ###
