"""empty message

Revision ID: 3f00187622ba
Revises: 63f905bc5153
Create Date: 2023-12-04 11:16:45.435852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f00187622ba'
down_revision = '63f905bc5153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_variables',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_variables')
    # ### end Alembic commands ###
