"""add keyword

Revision ID: 9fcfd9bb3764
Revises: aaf7de7f914c
Create Date: 2023-12-01 23:23:22.118631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcfd9bb3764'
down_revision = 'aaf7de7f914c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command', schema=None) as batch_op:
        batch_op.drop_column('keyword')

    # ### end Alembic commands ###
